# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [
  jekyll-feed,
  jekyll-seo-tag,
  jekyll-paginate,
  jekyll-sitemap,
  jekyll-redirect-from,
  jekyll-gist,
  jekyll-include-cache
]

# Customise atom feed settings
title: "Ronald Onyango"
author: "Ronald Onyango"
description:
  I am a strategic and data-driven Product Manager with over three years 
  of experience in product management, data analytics, and UX research 
  within social enterprise and digital-based sector businesses. My expertise 
  lies in leveraging data-driven insights, user research, and cross-functional 
  collaboration to drive impactful product strategies and innovative solutions 
  that enhance user experiences and business growth.

# Customise sitemap settings

sitemap: {
  path: sitemap.xml
}

# Customise redirect_from settings

redirect_from: {
  path: _redirects
}

