#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog',     url: 'blog'}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'Project One',   url: 'suicide-rates-analysis'}
- {name: 'Project Two',   url: 'proj-2'}
- {name: 'Project Three', url: 'proj-3'}
- {name: 'Project Four',  url: 'proj-4'}
- {name: 'Project Five',  url: 'proj-5'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter',   link: 'https://twitter.com/ronaldoyw'}
- {icon: 'instagram', link: 'https://instagram.com/ronaldoyw_'}
- {icon: 'github',    link: 'https://github.com/ronaldonyango'}
- {icon: 'linkedin',  link: 'https://linkedin.com/in/ronaldonyango'}
- {icon: 'envelope',  link: 'mailto:ronaldoyw@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

seo:
  description: 'I am a strategic and data-driven Product Manager with over three years 
  of experience in product management, data analytics, and UX research within social 
  enterprise and digital-based sector businesses. My expertise lies in leveraging 
  data-driven insights, user research, and cross-functional collaboration to drive 
  impactful product strategies and innovative solutions that enhance user experiences 
  and business growth.'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
# google-analytics-ua: 'G-VKHGE8W8W3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
