#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog',     url: 'blog'}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'Project One',   url: 'suicide-rates-analysis'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter',   link: 'https://twitter.com/ronaldoyw'}
- {icon: 'instagram', link: 'https://instagram.com/ronaldoyw_'}
- {icon: 'github',    link: 'https://github.com/ronaldonyango'}
- {icon: 'linkedin',  link: 'https://linkedin.com/in/ronaldonyango'}
- {icon: 'envelope',  link: 'mailto:ronaldoyw@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

seo:
  description: 'I am a strategic and data-driven Product Manager with over three years 
  of experience in product management, data analytics, and UX research within social 
  enterprise and digital-based sector businesses. My expertise lies in leveraging 
  data-driven insights, user research, and cross-functional collaboration to drive 
  impactful product strategies and innovative solutions that enhance user experiences 
  and business growth.'

#-------------------------------
# Google Analytics Section

# The measurement ID for Google Analytics 4
google-analytics-id: 'G-VKHGE8W8W3'

# Google Tag Manager Section

# The container ID for Google Tag Manager
google-tag-manager-id: 'GTM-5NLZQQK9'
